# -*- coding: utf-8 -*-
"""Hashing dan Sort Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbuomgvGlaT2yZuMVctiKQKrwfIyPAaC

Hashing
"""

# Fungsi untuk mencari sisa hasil bagi (modulus)
def mod(number, cellNumber):
    return number % cellNumber


# Contoh penggunaan fungsi mod()
# print(mod(400, 24))


# Fungsi untuk mengubah string menjadi nilai hash sederhana
def modASCII(string, cellNumber):

    total = 0

    # Menjumlahkan nilai ASCII setiap karakter
    for i in string:
        total += ord(i)

    # Hasil jumlah ASCII dibagi jumlah cell
    # lalu diambil sisanya
    return total % cellNumber


# Program utama dimulai dari sini

# Memanggil fungsi modASCII()
# "ABC" diubah ke nilai ASCII lalu dihitung hash-nya
print(modASCII("ABC", 24))

"""Quicksort"""

# Fungsi untuk menukar posisi dua elemen dalam list
def swap(my_list, index1, index2):
    my_list[index1], my_list[index2] = my_list[index2], my_list[index1]


# Menentukan posisi pivot yang sebenarnya
def pivot(my_list, pivot_index, end_index):

    # Menyimpan posisi pivot sementara
    swap_index = pivot_index

    # Mengecek semua elemen setelah pivot
    for i in range(pivot_index+1, end_index+1):

        # Jika ada nilai lebih kecil dari pivot
        if my_list[i] < my_list[pivot_index]:
            swap_index += 1

            # Pindahkan ke sebelah kiri pivot
            swap(my_list, swap_index, i)

    # Menempatkan pivot ke posisi yang benar
    swap(my_list, pivot_index, swap_index)

    return swap_index


# Fungsi utama quicksort (rekursif)
def quicksort_helper(my_list, left, right):

    # Berhenti jika bagian data tinggal 1 elemen
    if left < right:

        # Menentukan posisi pivot
        pivot_index = pivot(my_list, left, right)

        # Mengurutkan bagian kiri pivot
        quicksort_helper(my_list, left, pivot_index-1)

        # Mengurutkan bagian kanan pivot
        quicksort_helper(my_list, pivot_index+1, right)

    return my_list


# Memulai quicksort dari awal sampai akhir list
def quicksort(my_list):
    return quicksort_helper(my_list, 0, len(my_list)-1)


# Program utama

# Data yang akan diurutkan
my_list = [3,5,0,6,2,1,4]

# Menjalankan quicksort
print(quicksort(my_list))

"""Sorting Algorithms"""

import math
# Digunakan untuk fungsi matematika pada bucketSort()


# Fungsi sorting dibuat terlebih dahulu,
# lalu nanti dipanggil pada program utama sesuai kebutuhan.


def bubbleSort(customList):
    # Membandingkan nilai yang berdekatan,
    # jika salah urutan maka ditukar
    for i in range(len(customList)-1):
        for j in range(len(customList)-i-1):
            if customList[j] > customList[j+1]:
                customList[j], customList[j+1] = customList[j+1], customList[j]
    print(customList)



def selectionSort(customList):
    # Mencari nilai terkecil lalu menaruhnya di depan
    for i in range(len(customList)):
        min_index = i

        for j in range(i+1, len(customList)):
            if customList[min_index] > customList[j]:
                min_index = j

        customList[i], customList[min_index] = customList[min_index], customList[i]

    print(customList)



def insertionSort(customList):
    # Digunakan untuk mengurutkan data secara bertahap.
    # Fungsi ini juga dipakai oleh bucketSort()
    for i in range(1, len(customList)):
        key = customList[i]
        j = i-1

        while j >= 0 and key < customList[j]:
            customList[j+1] = customList[j]
            j -= 1

        customList[j+1] = key

    return customList



def bucketSort(customList):
    # Data dibagi menjadi beberapa bucket,
    # kemudian setiap bucket diurutkan dengan insertionSort()

    numberofBuckets = round(math.sqrt(len(customList)))
    maxValue = max(customList)
    arr = []

    for i in range(numberofBuckets):
        arr.append([])

    for j in customList:
        index_b = math.ceil(j*numberofBuckets/maxValue)
        arr[index_b-1].append(j)


    for i in range(numberofBuckets):
        arr[i] = insertionSort(arr[i])


    # Menggabungkan kembali semua bucket
    k = 0
    for i in range(numberofBuckets):
        for j in range(len(arr[i])):
            customList[k] = arr[i][j]
            k += 1

    return customList



# Merge dibuat terpisah karena mergeSort membutuhkan
# fungsi ini untuk menggabungkan data yang sudah dibagi.
def merge(customList, l, m, r):

    n1 = m - l + 1
    n2 = r - m

    L = [0] * n1
    R = [0] * n2


    for i in range(n1):
        L[i] = customList[l+i]

    for j in range(n2):
        R[j] = customList[m+1+j]


    i = 0
    j = 0
    k = l


    while i < n1 and j < n2:
        if L[i] <= R[j]:
            customList[k] = L[i]
            i += 1
        else:
            customList[k] = R[j]
            j += 1
        k += 1



def mergeSort(customList, l, r):
    # Data dibagi menjadi dua bagian,
    # kemudian digabung kembali menggunakan merge()

    if l < r:
        m = (l+(r-1))//2

        mergeSort(customList, l, m)
        mergeSort(customList, m+1, r)

        merge(customList, l, m, r)

    return customList



def partition(customList, low, high):
    # Membantu quickSort untuk menentukan posisi pivot

    i = low - 1
    pivot = customList[high]

    for j in range(low, high):
        if customList[j] <= pivot:
            i += 1
            customList[i], customList[j] = customList[j], customList[i]

    customList[i+1], customList[high] = customList[high], customList[i+1]

    return i+1



def quickSort(customList, low, high):
    # Mengurutkan data berdasarkan pivot

    if low < high:
        pi = partition(customList, low, high)

        quickSort(customList, low, pi-1)
        quickSort(customList, pi+1, high)



def heapify(customList, n, i):
    # Membantu heapSort membentuk struktur heap

    smallest = i
    l = 2*i + 1
    r = 2*i + 2

    if l < n and customList[l] < customList[smallest]:
        smallest = l

    if r < n and customList[r] < customList[smallest]:
        smallest = r

    if smallest != i:
        customList[i], customList[smallest] = customList[smallest], customList[i]

        heapify(customList, n, smallest)



def heapSort(customList):
    # HeapSort menggunakan heapify untuk mengurutkan data

    n = len(customList)

    # Membuat heap terlebih dahulu
    for i in range(int(n/2)-1, -1, -1):
        heapify(customList, n, i)


    # Mengambil elemen heap sampai data urut
    for i in range(n-1,0,-1):
        customList[i], customList[0] = customList[0], customList[i]

        heapify(customList, i, 0)



# Program utama mulai dijalankan dari sini

# Data yang akan diurutkan
cList = [2,1,7,6,5,3,4,9,8]


# Memanggil metode sorting yang ingin digunakan
heapSort(cList)


# Menampilkan hasil akhir
print(cList)