# -*- coding: utf-8 -*-
"""Hashing dan Sort Algorithm ( Latihan di Kelas).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbuomgvGlaT2yZuMVctiKQKrwfIyPAaC

Implementasi Hash Table Sederhana
"""

class HashTable:
    # Constructor, dijalankan saat objek dibuat
    def __init__(self, size):
        # Menyimpan ukuran hash table
        self.size = size

        # Membuat list berisi None sebanyak size
        # None menandakan slot masih kosong
        self.table = [None] * size

    # Fungsi hash menggunakan modulo (%)
    def hash_function(self, key):
        # Mengembalikan hasil key % ukuran tabel
        # return digunakan untuk mengembalikan nilai dari fungsi
        return key % self.size

    # Method untuk memasukkan data ke hash table
    def insert(self, key):
        # Menentukan index awal menggunakan hash function
        index = self.hash_function(key)

        # Selama slot belum kosong (bukan None)
        # maka cari slot berikutnya (Linear Probing)
        while self.table[index] is not None:
            # Geser ke index berikutnya
            # % self.size agar jika sampai index terakhir,
            # kembali ke index 0
            index = (index + 1) % self.size

        # Menyimpan data pada index yang ditemukan
        self.table[index] = key

    # Method untuk menampilkan isi hash table
    def display(self):
        # \n berarti pindah ke baris baru
        print("\nIsi Hash Table")

        # Mengulang karakter "-" sebanyak 30 kali
        print("-" * 30)

        # range(self.size) menghasilkan angka
        # dari 0 sampai self.size - 1
        for i in range(self.size):

            # Mengecek apakah slot kosong
            if self.table[i] is None:

                # f di depan string disebut f-string
                # digunakan untuk memasukkan nilai variabel ke dalam string
                # {i} akan diganti dengan nilai variabel i
                print(f"Index {i} : Empty")

            else:
                # {i} diganti index saat ini
                # {self.table[i]} diganti isi data pada index tersebut
                print(f"Index {i} : {self.table[i]}")


# Membuat objek HashTable dengan ukuran 10
hash_table = HashTable(10)

# List data yang akan dimasukkan
data = [25, 36, 47, 58, 69, 80]

# Mengambil setiap elemen dari list data
for item in data:

    # Memanggil method insert()
    # untuk memasukkan item ke hash table
    hash_table.insert(item)

# Memanggil method display()
# untuk menampilkan isi hash table
hash_table.display()

"""Mengurutkan Data Mahasiswa Menggunakan Quick Sort"""

# ==================================
# Fungsi Quick Sort
# ==================================

# def digunakan untuk membuat fungsi.
# Fungsi ini bernama quick_sort dan menerima data berupa list.
def quick_sort(data):

    # len() adalah fungsi bawaan Python untuk menghitung jumlah elemen dalam list.
    # Jika jumlah data 0 atau 1, data sudah pasti urut.
    if len(data) <= 1:
        return data

    # // adalah pembagian bulat.
    # len(data)//2 mencari posisi tengah list.
    # Nilai tengah dipakai sebagai pivot (nilai pembanding).
    pivot = data[len(data) // 2]

    # Membuat list kosong untuk menampung hasil pemisahan data.
    left = []     # nilai yang lebih kecil dari pivot
    middle = []   # nilai yang sama dengan pivot
    right = []    # nilai yang lebih besar dari pivot


    # for digunakan untuk melakukan perulangan.
    # item akan mengambil nilai dari data satu per satu.
    for item in data:

        # Jika item lebih kecil dari pivot,
        # masukkan ke list left.
        if item < pivot:
            # append() adalah fungsi list Python untuk menambahkan data ke akhir list.
            left.append(item)


        # Jika item sama dengan pivot,
        # masukkan ke list middle.
        elif item == pivot:
            middle.append(item)


        # Jika item lebih besar dari pivot,
        # masukkan ke list right.
        else:
            right.append(item)


    # Fungsi quick_sort dipanggil lagi untuk mengurutkan
    # bagian kiri dan kanan (rekursi).
    # Tanda + digunakan untuk menggabungkan list.
    return quick_sort(left) + middle + quick_sort(right)



# ==================================
# Program Utama
# ==================================

# Membuat list yang berisi nilai mahasiswa.
nilai = [78, 65, 90, 88, 55, 72, 95, 60, 84, 70]


# print() adalah fungsi Python untuk menampilkan teks atau nilai ke layar.
print("Data Awal")

# Menampilkan isi list nilai.
print(nilai)



# Memanggil fungsi quick_sort untuk mengurutkan data.
# Hasilnya disimpan ke variabel hasil.
hasil = quick_sort(nilai)



# Menampilkan hasil setelah diurutkan.
print("\nData Setelah Quick Sort")
print(hasil)



# len() digunakan untuk menghitung jumlah elemen dalam list.
# Contoh: len([55,60,65]) hasilnya 3.
jumlah_data = len(hasil)


# min() adalah fungsi Python untuk mencari nilai terkecil dalam list.
nilai_min = min(hasil)


# max() adalah fungsi Python untuk mencari nilai terbesar dalam list.
nilai_max = max(hasil)


# sum() adalah fungsi Python untuk menjumlahkan semua nilai dalam list.
# Dibagi jumlah_data untuk mencari rata-rata.
rata_rata = sum(hasil) / jumlah_data



# Menampilkan judul statistik.
print("\nStatistik Data")


# Mengulang tanda "-" sebanyak 22 kali.
# Operator * pada string digunakan untuk mengulang teks.
print("----------------------")


# Menampilkan jumlah data.
print("Jumlah Data :", jumlah_data)


# Menampilkan nilai terkecil.
print("Nilai Minimum :", nilai_min)


# Menampilkan nilai terbesar.
print("Nilai Maksimum :", nilai_max)


# round() digunakan untuk membulatkan angka.
# Angka 2 berarti jumlah angka di belakang koma.
print("Nilai Rata-rata :", round(rata_rata, 2))

"""Perbandingan Bubble Sort dan Merge Sort

"""

import time
# Mengimpor library time dari Python.
# Digunakan untuk menghitung waktu eksekusi program.


# ==========================================
# Bubble Sort
# ==========================================

def bubble_sort(data):
    # Membuat fungsi bubble_sort.
    # Fungsi ini menerima data berupa list untuk diurutkan.

    arr = data.copy()
    # copy() digunakan untuk membuat salinan data.
    # Agar data asli tidak berubah saat proses sorting.

    comparison = 0
    # Menyimpan jumlah perbandingan angka.

    swap = 0
    # Menyimpan jumlah pertukaran posisi angka.

    n = len(arr)
    # len() digunakan untuk menghitung jumlah elemen dalam list.
    # Nilainya disimpan ke variabel n.


    for i in range(n):
        # for digunakan untuk perulangan.
        # range(n) mengulang sebanyak jumlah data.


        for j in range(0, n - i - 1):
            # Perulangan untuk membandingkan angka yang bersebelahan.
            # n-i-1 mengurangi pengecekan karena bagian belakang sudah urut.


            comparison += 1
            # Menambah jumlah perbandingan sebanyak 1.


            if arr[j] > arr[j + 1]:
                # Mengecek apakah angka kiri lebih besar dari kanan.
                # Jika benar, posisi angka harus ditukar.


                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                # Menukar posisi dua angka.


                swap += 1
                # Menambah jumlah pertukaran.


    return arr, comparison, swap
    # Mengembalikan hasil:
    # 1. Data yang sudah urut
    # 2. Jumlah perbandingan
    # 3. Jumlah swap



# ==========================================
# Merge Sort
# ==========================================

comparison_merge = 0
# Variabel untuk menghitung perbandingan Merge Sort.

swap_merge = 0
# Variabel untuk menghitung pemindahan data Merge Sort.


def merge_sort(arr):
    # Membuat fungsi merge_sort.
    # Digunakan untuk mengurutkan data dengan Merge Sort.


    global comparison_merge
    global swap_merge
    # global digunakan agar variabel luar fungsi
    # bisa diubah dari dalam fungsi.


    if len(arr) <= 1:
        return arr
    # len() menghitung jumlah data.
    # Jika data hanya 1 atau kosong, langsung dikembalikan
    # karena sudah dianggap urut.


    mid = len(arr) // 2
    # // adalah pembagian bulat.
    # Digunakan untuk mencari posisi tengah data.


    left = merge_sort(arr[:mid])
    # arr[:mid] mengambil bagian kiri list.
    # Lalu bagian kiri diurutkan lagi.


    right = merge_sort(arr[mid:])
    # arr[mid:] mengambil bagian kanan list.
    # Lalu bagian kanan diurutkan lagi.


    return merge(left, right)
    # Menggabungkan bagian kiri dan kanan
    # yang sudah diurutkan.



def merge(left, right):
    # Fungsi untuk menggabungkan dua list yang sudah urut.


    global comparison_merge
    global swap_merge
    # Mengakses variabel penghitung dari luar fungsi.


    result = []
    # Membuat list kosong untuk menyimpan hasil gabungan.


    i = 0
    # Index untuk membaca data bagian kiri.


    j = 0
    # Index untuk membaca data bagian kanan.



    while i < len(left) and j < len(right):
        # while berjalan selama data kiri dan kanan masih ada.


        comparison_merge += 1
        # Menambah jumlah perbandingan.


        if left[i] < right[j]:
            # Membandingkan nilai kiri dan kanan.


            result.append(left[i])
            # append() digunakan untuk menambahkan data ke list hasil.


            i += 1
            # Berpindah ke data kiri berikutnya.


        else:

            result.append(right[j])
            # Jika kanan lebih kecil, masukkan nilai kanan.


            j += 1
            # Berpindah ke data kanan berikutnya.


        swap_merge += 1
        # Menghitung pemindahan data.



    while i < len(left):
        # Jika masih ada sisa data di kiri.


        result.append(left[i])
        # Tambahkan sisa data kiri.


        i += 1
        # Pindah ke data kiri berikutnya.



    while j < len(right):
        # Jika masih ada sisa data di kanan.


        result.append(right[j])
        # Tambahkan sisa data kanan.


        j += 1
        # Pindah ke data kanan berikutnya.



    return result
    # Mengembalikan hasil penggabungan.



# ==========================================
# Program Utama
# ==========================================

data = [54, 23, 87, 12, 65, 34, 98, 41, 19, 76]
# Membuat list data yang akan diuji.


print("Data Awal")
# print() digunakan untuk menampilkan teks.


print(data)
# Menampilkan isi data.



# Bubble Sort

start = time.perf_counter()
# Mengambil waktu mulai proses.


bubble_result, bubble_compare, bubble_swap = bubble_sort(data)
# Menjalankan Bubble Sort.
# Hasilnya disimpan ke 3 variabel:
# hasil data, jumlah perbandingan, jumlah swap.


bubble_time = (time.perf_counter() - start) * 1000
# Menghitung waktu proses.
# Dikalikan 1000 agar hasil dalam milidetik (ms).



# Merge Sort

start = time.perf_counter()
# Mengambil waktu mulai Merge Sort.


merge_result = merge_sort(data.copy())
# Menjalankan Merge Sort.
# copy() membuat salinan data agar data asli aman.


merge_time = (time.perf_counter() - start) * 1000
# Menghitung waktu Merge Sort.



# ==========================================
# Output
# ==========================================

print("\n==============================")
# \n membuat baris baru.


print("BUBBLE SORT")
# Menampilkan judul.


print("Data :", bubble_result)
# Menampilkan hasil Bubble Sort.


print("Comparison :", bubble_compare)
# Menampilkan jumlah perbandingan.


print("Swap :", bubble_swap)
# Menampilkan jumlah pertukaran.


print("Execution Time : %.5f ms" % bubble_time)
# %.5f digunakan untuk menampilkan angka
# dengan 5 angka di belakang koma.



print("\n==============================")
print("MERGE SORT")


print("Data :", merge_result)
# Menampilkan hasil Merge Sort.


print("Comparison :", comparison_merge)
# Menampilkan jumlah perbandingan Merge Sort.


print("Swap :", swap_merge)
# Menampilkan jumlah pemindahan data.


print("Execution Time : %.5f ms" % merge_time)
# Menampilkan waktu eksekusi Merge Sort.

"""Sistem Pencarian Produk Menggunakan Hash Table

"""

# ==========================================
# Class Product
# ==========================================

class Product:
    # Membuat class Product untuk menyimpan data produk.

    def __init__(self, code, name):
        # Constructor, dijalankan saat objek Product dibuat.
        # code = kode produk, name = nama produk.

        self.code = code
        # Menyimpan kode produk.

        self.name = name
        # Menyimpan nama produk.


    def __str__(self):
        # Mengatur tampilan objek ketika diprint.

        return f"Kode : {self.code} | Nama : {self.name}"
        # f-string digunakan untuk memasukkan nilai variabel ke dalam teks.
        # {self.code} akan berisi kode produk.
        # {self.name} akan berisi nama produk.



# ==========================================
# Class HashTable
# ==========================================

class HashTable:
    # Membuat class HashTable untuk menyimpan data produk.

    def __init__(self, size):

        self.size = size
        # Menyimpan ukuran hash table.


        self.table = [[] for _ in range(size)]
        # Membuat hash table berupa list kosong.
        # Setiap index memiliki list untuk menyimpan data jika terjadi collision.



    def hash_function(self, key):
        # Fungsi hash untuk menentukan posisi data.

        return key % self.size
        # Menggunakan modulo untuk menentukan index.
        # Contoh: 101 % 7 = 3, jadi masuk index 3.



    def insert(self, product):
        # Fungsi untuk memasukkan data produk ke hash table.

        index = self.hash_function(product.code)
        # Menghitung index berdasarkan kode produk.


        self.table[index].append(product)
        # append() menambahkan produk ke dalam list pada index tersebut.
        # Jika index sudah ada isi, data tetap ditambahkan (chaining).



    def search(self, code):
        # Fungsi untuk mencari produk berdasarkan kode.
        # Bagian ini adalah kode pencarian.


        index = self.hash_function(code)
        # Mencari lokasi index berdasarkan kode yang dicari.


        bucket = self.table[index]
        # Mengambil isi list pada index tersebut.


        for product in bucket:
            # Mengecek setiap produk di dalam index tersebut.

            if product.code == code:
                # Membandingkan kode produk dengan kode yang dicari.

                return product
                # Mengembalikan produk jika ditemukan.


        return None
        # Jika tidak ditemukan, mengembalikan None.



    def display(self):
        # Fungsi untuk menampilkan isi hash table.


        print("\nIsi Hash Table")

        print("--------------------------------")


        for i in range(self.size):
            # Mengecek setiap index pada hash table.


            print(f"Index {i} :", end=" ")
            # f-string digunakan agar nilai i bisa masuk ke teks.
            # end=" " membuat output tetap di baris yang sama.


            if len(self.table[i]) == 0:
                # len() menghitung jumlah isi list.
                # Jika 0 berarti index kosong.

                print("Empty")


            else:

                for product in self.table[i]:
                    # Mengambil setiap produk di dalam index tersebut.


                    print(f"[{product.code}-{product.name}]", end=" ")
                    # Menampilkan kode dan nama produk.


                print()
                # Pindah ke baris baru.



# ==========================================
# Program Utama
# ==========================================

hash_table = HashTable(7)
# Membuat hash table dengan ukuran 7.



data_produk = [
    Product(101, "Laptop"),
    Product(102, "Mouse"),
    Product(103, "Keyboard"),
    Product(104, "Monitor"),
    Product(105, "Printer"),
    Product(106, "Speaker"),
    Product(107, "Flashdisk"),
    Product(108, "Webcam")
]
# Membuat objek produk berisi kode dan nama.



for produk in data_produk:
    # Mengambil setiap data produk.

    hash_table.insert(produk)
    # Memasukkan produk ke hash table.



hash_table.display()
# Menampilkan isi hash table.



kode = int(input("Masukkan kode produk : "))
# input() menerima kode dari user.
# int() mengubah input menjadi angka.



hasil = hash_table.search(kode)
# Memanggil fungsi search untuk mencari produk.
# Pencarian dilakukan berdasarkan kode produk.



if hasil:
    # Jika hasil pencarian tidak kosong, berarti ditemukan.

    print("\nProduk ditemukan")

    print("---------------------")

    print("Kode :", hasil.code)
    # Menampilkan kode produk.

    print("Nama :", hasil.name)
    # Menampilkan nama produk.


else:
    # Jika hasil pencarian None.

    print("\nProduk tidak ditemukan.")

"""Mini Project: Sistem Ranking Penjualan Toko Online Menggunakan Hash dan Sorting"""

# ==========================================
# CLASS PRODUCT
# ==========================================

class Product:
    # Membuat class Product sebagai tempat menyimpan data produk


    def __init__(self, id_produk, nama, kategori, harga, terjual):
        # Constructor, dijalankan saat objek Product dibuat
        # Parameter berisi data produk


        self.id = id_produk
        # Menyimpan ID produk ke dalam objek


        self.nama = nama
        # Menyimpan nama produk


        self.kategori = kategori
        # Menyimpan kategori produk


        self.harga = harga
        # Menyimpan harga produk


        self.terjual = terjual
        # Menyimpan jumlah produk yang terjual



    def tampil(self):
        # Fungsi untuk menampilkan informasi produk


        print("-------------------------------")
        print("ID        :", self.id)
        # Menampilkan ID produk


        print("Nama      :", self.nama)
        # Menampilkan nama produk


        print("Kategori  :", self.kategori)
        # Menampilkan kategori produk


        print("Harga     :", self.harga)
        # Menampilkan harga produk


        print("Terjual   :", self.terjual)
        # Menampilkan jumlah produk yang sudah terjual


        print("-------------------------------")



# ==========================================
# CLASS HASH TABLE
# ==========================================

class HashTable:
    # Membuat class HashTable untuk menyimpan data menggunakan hash


    def __init__(self, size):

        self.size = size
        # Menyimpan ukuran hash table


        self.table = [None] * size
        # Membuat array kosong sesuai ukuran hash table
        # None berarti index belum memiliki data



    def hash_function(self, key):
        # Fungsi hash untuk menentukan lokasi penyimpanan


        return key % self.size
        # Menggunakan modulo untuk menentukan index
        # Contoh: 101 % 11 = 2
        # Produk masuk ke index 2



    def insert(self, product):
        # Fungsi untuk memasukkan data produk


        index = self.hash_function(product.id)
        # Menghitung index berdasarkan ID produk



        while self.table[index] is not None:
            # Mengecek apakah index sudah terisi


            index = (index + 1) % self.size
            # Jika index penuh, pindah ke index berikutnya
            # Ini adalah Linear Probing untuk menangani collision



        self.table[index] = product
        # Menyimpan produk ke index yang kosong



    def search(self, id_produk):
        # Fungsi untuk mencari produk berdasarkan ID


        index = self.hash_function(id_produk)
        # Menghitung lokasi awal pencarian berdasarkan ID


        start = index
        # Menyimpan posisi awal pencarian
        # Digunakan agar pencarian berhenti jika kembali ke awal



        while self.table[index] is not None:
            # Melakukan pencarian selama index masih ada data


            if self.table[index].id == id_produk:
                # Mengecek apakah ID produk sama dengan yang dicari


                return self.table[index]
                # Mengembalikan data produk jika ditemukan



            index = (index + 1) % self.size
            # Jika tidak cocok, pindah ke index berikutnya



            if index == start:
                # Jika kembali ke posisi awal
                # berarti semua index sudah diperiksa


                break



        return None
        # Mengembalikan kosong jika produk tidak ditemukan



    def get_all_products(self):
        # Fungsi mengambil semua data produk dalam hash table


        data = []
        # Membuat list kosong untuk menyimpan produk


        for item in self.table:
            # Mengecek setiap isi hash table


            if item is not None:
                # Jika index memiliki data


                data.append(item)
                # Menambahkan produk ke list data



        return data
        # Mengembalikan semua produk



# ==========================================
# QUICK SORT
# ==========================================

def quick_sort(data, key):
    # Fungsi Quick Sort untuk mengurutkan data
    # key menentukan atribut yang digunakan untuk sorting


    if len(data) <= 1:
        # len() menghitung jumlah data
        # Jika data hanya 1 atau kosong, data sudah urut


        return data



    pivot = getattr(data[len(data)//2], key)
    # getattr() mengambil nilai atribut dari objek
    #
    # len(data)//2 mengambil posisi tengah data
    # Contoh key = "terjual"
    # maka mengambil nilai penjualan produk tengah



    left = []
    # Menyimpan data yang nilainya lebih besar dari pivot


    middle = []
    # Menyimpan data yang nilainya sama dengan pivot


    right = []
    # Menyimpan data yang nilainya lebih kecil dari pivot



    for item in data:
        # Mengulang setiap produk dalam data


        nilai = getattr(item, key)
        # Mengambil nilai atribut sesuai key



        if nilai > pivot:
            # Jika nilai lebih besar dari pivot


            left.append(item)
            # Memasukkan data ke bagian kiri



        elif nilai == pivot:
            # Jika nilai sama dengan pivot


            middle.append(item)
            # Memasukkan data ke bagian tengah



        else:

            right.append(item)
            # Memasukkan data ke bagian kanan



    return quick_sort(left, key) + middle + quick_sort(right, key)
    # Mengurutkan bagian kiri dan kanan
    # lalu menggabungkan hasilnya



# ==========================================
# DATA AWAL
# ==========================================

hash_table = HashTable(11)
# Membuat hash table ukuran 11
# Sesuai rumus Hash(ID) = ID % 11



produk_awal = [
    # List berisi data produk awal


    Product(101, "Laptop", "Elektronik", 8000000, 120),
    Product(102, "Mouse", "Aksesoris", 150000, 450),
    Product(103, "Keyboard", "Aksesoris", 300000, 350),
    Product(104, "Monitor", "Elektronik", 2500000, 180),
    Product(105, "Printer", "Elektronik", 1800000, 90),
    Product(106, "Speaker", "Audio", 450000, 250)

]


for item in produk_awal:
    # Mengulang semua produk awal


    hash_table.insert(item)
    # Memasukkan setiap produk ke hash table



# ==========================================
# MENU
# ==========================================

while True:
    # Membuat program terus berjalan sampai user memilih keluar


    print("\n=================================")
    print("ONLINE STORE MANAGEMENT")
    print("=================================")

    print("1. Tambah Produk")
    print("2. Cari Produk")
    print("3. Tampilkan Semua Produk")
    print("4. Ranking Penjualan")
    print("5. Update Penjualan")
    print("6. Statistik")
    print("7. Keluar")


    pilihan = input("Pilih menu : ")
    # input() mengambil pilihan dari user



    if pilihan == "1":
        # Menu untuk menambah produk


        id_produk = int(input("ID Produk : "))
        # int() mengubah input menjadi angka


        nama = input("Nama Produk : ")
        # Mengambil nama produk


        kategori = input("Kategori : ")
        # Mengambil kategori produk


        harga = int(input("Harga : "))
        # Mengambil harga produk


        terjual = int(input("Jumlah Terjual : "))
        # Mengambil jumlah penjualan



        baru = Product(id_produk, nama, kategori, harga, terjual)
        # Membuat objek Product baru



        hash_table.insert(baru)
        # Menyimpan produk baru ke hash table



        print("Produk berhasil ditambahkan.")



    elif pilihan == "2":
        # Menu pencarian produk


        cari = int(input("Masukkan ID Produk : "))
        # Meminta ID yang ingin dicari


        hasil = hash_table.search(cari)
        # Mencari produk menggunakan fungsi search



        if hasil:
            # Jika produk ditemukan


            print("\nProduk ditemukan")


            hasil.tampil()
            # Menampilkan data produk



        else:

            print("Produk tidak ditemukan.")
            # Jika produk tidak ditemukan



    elif pilihan == "3":

        semua = hash_table.get_all_products()
        # Mengambil semua produk dari hash table


        print()


        for item in semua:
            # Mengulang semua produk


            item.tampil()
            # Menampilkan produk



    elif pilihan == "4":

        semua = hash_table.get_all_products()
        # Mengambil semua data produk


        ranking = quick_sort(semua, "terjual")
        # Mengurutkan produk berdasarkan jumlah penjualan



        print("\n===== RANKING PENJUALAN =====\n")


        nomor = 1
        # Variabel nomor ranking awal



        for item in ranking:
            # Mengulang hasil ranking


            print(
                nomor,
                item.nama,
                "-",
                item.terjual,
                "unit"
            )
            # Menampilkan urutan, nama produk, dan jumlah terjual



            nomor += 1
            # Menambah nomor ranking



    elif pilihan == "5":

        cari = int(input("ID Produk : "))
        # Meminta ID produk


        hasil = hash_table.search(cari)
        # Mencari produk berdasarkan ID



        if hasil:

            tambahan = int(input("Tambahan Penjualan : "))
            # Mengambil jumlah penjualan tambahan


            hasil.terjual += tambahan
            # Menambahkan jumlah penjualan lama



            print("Data berhasil diperbarui.")



        else:

            print("Produk tidak ditemukan.")



    elif pilihan == "6":

        semua = hash_table.get_all_products()
        # Mengambil semua produk



        total_produk = len(semua)
        # len() menghitung jumlah produk



        total_penjualan = 0
        # Variabel untuk menyimpan total penjualan



        produk_terlaris = semua[0]
        # Produk pertama sebagai nilai awal terlaris



        produk_termurah = semua[0]
        # Produk pertama sebagai nilai awal termurah



        produk_termahal = semua[0]
        # Produk pertama sebagai nilai awal termahal



        for item in semua:

            total_penjualan += item.terjual
            # Menjumlahkan semua penjualan



            if item.terjual > produk_terlaris.terjual:
                # Mengecek produk dengan penjualan terbesar


                produk_terlaris = item



            if item.harga < produk_termurah.harga:
                # Mengecek harga paling murah


                produk_termurah = item



            if item.harga > produk_termahal.harga:
                # Mengecek harga paling mahal


                produk_termahal = item



        print("\n========== STATISTIK ==========")


        print("Total Produk :", total_produk)
        # Menampilkan jumlah produk


        print("Total Penjualan :", total_penjualan)
        # Menampilkan total semua penjualan


        print("Produk Terlaris :", produk_terlaris.nama)
        # Menampilkan produk dengan penjualan terbanyak


        print("Produk Termurah :", produk_termurah.nama)
        # Menampilkan produk harga paling murah


        print("Produk Termahal :", produk_termahal.nama)
        # Menampilkan produk harga paling mahal



    elif pilihan == "7":

        print("Program selesai.")


        break
        # Menghentikan perulangan dan keluar program



    else:

        print("Pilihan tidak tersedia.")
        # Jika menu yang dimasukkan tidak ada